version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '07:00'
      timezone: Europe/Budapest
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - javascript
    groups:
      tooling:
        patterns:
          - '@eslint/*'
          - eslint
          - globals
          - prettier
          - typescript
          - typescript-eslint
          - vite
          - vite-plugin-monkey
          - vitest
        update-types:
          - minor
          - patch
      test-environment:
        patterns:
          - jsdom

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '07:30'
      timezone: Europe/Budapest
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions:
        patterns:
          - '*'
