overrides:
  brace-expansion@<1.1.16: 1.1.16
  brace-expansion@>=4.0.0 <5.0.8: 5.0.8
  minimatch@<3.1.4: 3.1.4
  minimatch@>=10.0.0 <10.2.5: 10.2.5
  picomatch@<4.0.4: 4.0.4
  postcss@<8.5.18: 8.5.18

allowBuilds:
  esbuild: true
